[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:setup && npm run start:prod"
healthcheckPath = "/api-docs"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
